### ISSUE TITLE
chat.openai.com closes itself automatically if opened manually in the browser

### ISSUE THREAD

**Issue by BingeCode** [yaroslav-n/tweetGPT#1]
Steps to reproduce:

Generate tweet by clicking TweetGPT icon
TweetGPT opens chatGPT window
Error
TweetGPT closes window
Icon turns temporarily red
I try to open chat.openai.com/chat manually in the browser
It immediately closes upon loading
I try again
Same result
I delete the extension
Now the window stays open when I load chatGPT

**Comment by yaroslav-n** [comment]
Thank you for the bug report.
I'll try to fix it this week.

**Comment by vrindavan** [comment]
If this helps:
![image](https://user-images.githubusercontent.com/50140643/208909745-242235ce-7f1c-46a5-b6de-b3c57626e089.png)

**Comment by vrindavan** [comment]
Few of these:

![image](https://user-images.githubusercontent.com/50140643/208910268-767cdf9b-cd14-451c-8546-623c7389150a.png)
![image](https://user-images.githubusercontent.com/50140643/208910300-5cae6869-dac3-4072-8813-0d79b1e20b64.png)
![image](https://user-images.githubusercontent.com/50140643/208910333-58d9e855-5750-45eb-a1f5-33cb6a902069.png)

**Comment by vrindavan** [comment]
This solves the issue in Brave: https://github.com/wong2/chat-gpt-google-extension#how-to-make-it-work-in-brave

**Comment by arjun-ms** [comment]
Facing the same error @yaroslav-n @BingeCode 
![image](https://user-images.githubusercontent.com/64315213/211178696-e7cc603d-cfdd-49d4-914a-1c9edfffc17c.png)

**Comment by yaroslav-n** [comment]
This should now be fixed with the latest update.
