### ISSUE TITLE
Allow for topical tweets and replies

### ISSUE THREAD

**Issue by brandonmcconnell** [yaroslav-n/tweetGPT#2]
It'd be neat to be able to include a prompt/subject for our tweet/reply to guide ChatGPT to write a more specific tweet.

Maybe in the tweet box, I could say something like "cheer for Argentina after their world cup victory"

This could translate in ChatGPT to something like this:
> Write a tweet about "cheer for Argentina after their world cup victory"

<img width="706" alt="screenshot of ChatGPT writing tweet example" src="https://user-images.githubusercontent.com/5913254/208579800-7ccb3403-29b6-4fbe-911c-4e3c373079c5.png">

**Comment by yaroslav-n** [comment]
I kinda stopped active development of this extension for now but will put it into a ToDo list. 
Also, if somebody wants to do a PR for this, I'll gladly merge it.

**Comment by yaroslav-n** [comment]
This feature is now released with v2 version.
