### ISSUE TITLE
No Reply Generated

### ISSUE THREAD

**Issue by harisdev-netizen** [yaroslav-n/tweetGPT#5]
I am using TweetGPT to generate replies for tweets, but I am facing an issue where it opens the chat.opanai window but does not generate any reply. I have followed the instructions provided in the documentation and have provided the required authentication keys, but I am still not getting any response from the model.

Actual behavior:
The chat.opanai window opens, but no reply is generated.

**Comment by yaroslav-n** [comment]
Thank you for the feedback!
The OpenAI team has updated its website, and the authorisation in the first version of this extension no longer works.
But good news - I've just merged a v2 of the extension, which no longer requires authorisation in chatGPT.  So this issue should be fixed
